name: Docker Image MariaDB
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - mariadb/**
      - .github/workflows/mariadb.yml

jobs:
  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "10.0"
          - "10.1"
          - "10.2"
          - "10.3"
          - "10.4"
          - "10.5"
          - "10.6"
          - "10.7"
          - "10.8"
          - "10.9"
          - "10.10"
          - "10.11"
          - "11.0"
          - "11.1"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v3
        with:
          context: mariadb
          platforms: linux/amd64,linux/arm64
          build-args: MARIADB_VERSION=${{ matrix.version }}${{ matrix.modifier }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/mariadb:${{ matrix.version }}${{ matrix.modifier }},${{ secrets.IMAGE_REPOSITORY }}/mariadb:${{matrix.version}}${{matrix.modifier}}
