name: Docker Image RabbitMQ
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - rabbitmq/**
      - .github/workflows/rabbitmq.yml

jobs:
  rabbitmq:
    name: RabbitMQ
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v3
        with:
          context: rabbitmq
          platforms: linux/amd64,linux/arm64
          build-args: RABBITMQ_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/rabbitmq:${{ matrix.version }},${{ secrets.IMAGE_REPOSITORY }}/rabbitmq:${{matrix.version}}
